Repository CS-CT/Coding-Test, pull requests merged in 2023-03, with the labels that each got.

#42 BaekJoon / [silver 1] 회의실 배정
  백준/회의실배정/회의실배정.java
  백준/회의실배정/회의실배정.md
Labels: greedy

#41 inflearn / Allocation of Conference Rooms, Sumo Wrestle
  Jen/Allocation of Conference Rooms/Allocation of Conference Rooms.md
  Jen/Allocation of Conference Rooms/Allocation of Conference Rooms.py
  Jen/Sumo Wrestle/Sumo Wrestle.md
  Jen/Sumo Wrestle/Sumo Wrestle.py
Labels: greedy

#43 BaekJoon / [silver 2] 특정거리의도시찾기, 최단경로
  백준/최단경로/최단경로.java
  백준/최단경로/최단경로.md
  백준/특정거리의도시찾기/특정거리의도시찾기.java
  백준/특정거리의도시찾기/특정거리의도시찾기.md
Labels: BFS, Dijkstra

#44 Programmers / [level 2] 덧칠하기, 혼자 놀기의 달인
  JT/덧칠하기/덧칠하기.md
  JT/덧칠하기/덧칠하기.py
  JT/혼자 놀기의 달인/혼자 놀기의 달인.md
  JT/혼자 놀기의 달인/혼자 놀기의 달인.py
Labels: sliding window

#46 Programmers / [level 2] 다리를 지나는 트럭
  다리를 지나는 트럭/다리를 지나는 트럭.md
  다리를 지나는 트럭/다리를 지나는 트럭.py
Labels: queue

#47 Programmers / [level 3] 아이템 줍기, [level 2] 이모티콘 할인행사, 혼자서 하는 틱택토, BaekJoon / [gold 2] 퍼즐
  JT/아이템 줍기/아이템 줍기.md
  JT/아이템 줍기/아이템 줍기.py
  JT/이모티콘 할인행사/이모티콘 할인행사.md
  JT/이모티콘 할인행사/이모티콘 할인행사.py
  JT/퍼즐/퍼즐.md
  JT/퍼즐/퍼즐.py
  JT/혼자 놀기의 달인/혼자 놀기의 달인.py
  JT/혼자서 하는 틱택토/혼자서 하는 틱택토.md
  JT/혼자서 하는 틱택토/혼자서 하는 틱택토.py
Labels: BFS, exhaustive search

#48 Programmers / [level 2] 이모티콘 할인행사
  이모티콘 할인 행사/이모티콘 할인 행사.md
  이모티콘 할인 행사/이모티콘 할인 행사.py
Labels: exhaustive search

#49 BaekJoon / [Gold 4] 좋다
  백준/DNA비밀번호/DNA비밀번호.java
  백준/DNA비밀번호/DNA비밀번호.md
  백준/좋다/좋다.java
  백준/좋다/좋다.md
  백준/최단경로/최단경로.java
Labels: two pointer

#50 BaekJoon / [Gold 4] 좋다
  좋다/좋다.md
  좋다/좋다.py
Labels: exhaustive search, two pointer

#51 Programmers / [level 2] 두 큐 합 같게하기
  두 큐 합 같게하기/두 큐 합 같게하기.md
  두 큐 합 같게하기/두 큐 합 같에하기.py
Labels: queue

#52 Programmers / [level 3] 디스크 컨트롤러
  디스크 컨트롤러/디스크 컨트롤러.md
  디스크 컨트롤러/디스크 컨트롤러.py
Labels: priority queue

#53 BaekJoon / [Gold 4] 오큰수
  백준/오큰수/SampleFile.md
  백준/오큰수/오큰수.java
Labels: stack

#54 Programmers/ [level 3] 이중 우선순위 큐
  이중 우선순위 큐/이중 우선순위 큐.md
  이중 우선순위 큐/이중 우선순위 큐.py
Labels: priority queue

#55 Programmers / [level 2] 교점에 별 만들기, 전력망을 둘로 나누기
  JT/교점에 별 만들기/교점에 별 만들기.md
  JT/교점에 별 만들기/교점에 별 만들기.py
  JT/전력망을 둘로 나누기/전력망을 둘로 나누기.md
  JT/전력망을 둘로 나누기/전력망을 둘로 나누기.py
Labels: implementation, BFS, exhaustive search

#56 Programmers / [level 3] 연속 펄스 부분 수열의 합
  연속 펄스 부분 수열의 합/연속 펄스 부분 수열의 합.md
  연속 펄스 부분 수열의 합/연속 펄스 부분 수열의 합.py
Labels: DP

#57 Programmers / [level 2] Tower of Hanoi
  Jen/Tower of Hanoi/Tower of Hanoi.md
  Jen/Tower of Hanoi/Tower of Hanoi.py
Labels: recursive call

#58 Programmers / [level 2] 행렬 테두리 회전하기, [level 3] 연속 펄스 부분 수열의 합
  JT/연속 펄스 부분 수열의 합/연속 펄스 부분 수열의 합.md
  JT/연속 펄스 부분 수열의 합/연속 펄스 부분 수열의 합.py
  JT/행렬 테두리 회전하기/행렬 테두리 회전하기.md
  JT/행렬 테두리 회전하기/행렬 테두리 회전하기.py
Labels: implementation, DP

#59 Programmers / [level 3] 표현 가능한 이진트리
  표현 가능한 이진트리/표현 가능한 이진트리.md
  표현 가능한 이진트리/표현 가능한 이진트리.py
Labels: binary tree

#60 BaekJoon / [Silver 1] 절댓값힙
  백준/절댓값힙/절댓값힙.java
  백준/절댓값힙/절댓값힙.md
Labels: priority queue

#61 inflearn / Sinking Titanic
  Jen/Sinking Titanic/Sinking Titanic.md
  Jen/Sinking Titanic/Sinking Titanic.py
Labels: greedy

#62 Programmers / [level 3] 미로 탈출 명령어
  미로 탈출 명령어/미로 탈출 명령어.md
  미로 탈출 명령어/미로 탈출 명령어.py
  표 편집/표 편집.md
  표 편집/표 편집.py
  표 편집/표편집.java
Labels: greedy, BFS

#65 Programmers / [level 3] 표 편집
  표 편집/표 편집.md
  표 편집/표 편집.py
  표 편집/표편집.java
Labels: linked list

#66 LeetCode / [Medium] Insertion Sort List
  Jen/Insertion Sort List/Insertion Sort List.md
  Jen/Insertion Sort List/Insertion Sort List.py
Labels: sorting

#68 Programmers [level 2] Functional Development
  Jen/Functional Development/Functional Development.md
  Jen/Functional Development/Functional Development.py
Labels: queue

#69 Programmers / [level 1] 가장 가까운 같은 글자
  SampleFile.md
  가장 가까운 같은 글자/가장 가까운 같은 글자.java
  가장 가까운 같은 글자/가장 가까운 같은 글자.md
Labels: hash

#71 Programmers [level 2] Minimize Compensation Cost
  Jen/Minimize Compensation Cost/Minimize Compensation Cost.md
  Jen/Minimize Compensation Cost/Minimize Compensation Cost.py
Labels: heap

#70 Programmers / [level 2] 배달
  배달/배달.java
  배달/배달.md
  배달/배달.py
Labels: Dijkstra

#73 Programmers / [level 3] N으로 표현
  N으로 표현/N으로 표현.java
  N으로 표현/N으로 표현.md
  N으로 표현/N으로 표현.py
Labels: DP

#72 Programmers, BaekJoon / [level 1] 완주하지 못한 선수, 포켓몬, [level 2] 전화번호목록, [Silver 3] 이친수
  백준/이친수/이친수.java
  프로그래머스/완주하지못한선수/Solution.java
  프로그래머스/완주하지못한선수/완주하지못한선수.md
  프로그래머스/전화번호목록/Solution.java
  프로그래머스/전화번호목록/전화번호목록.md
  프로그래머스/포켓몬/Solution.java
  프로그래머스/포켓몬/포켓몬.md
Labels: hash

#75 Programmers / [level 2] 전화번호 목록
  백준/이친수/이친수.java
  프로그래머스/완주하지못한선수/Solution.java
  프로그래머스/완주하지못한선수/완주하지못한선수.md
  프로그래머스/전화번호목록/Solution.java
  프로그래머스/전화번호목록/전화번호목록.md
  프로그래머스/포켓몬/Solution.java
  프로그래머스/포켓몬/포켓몬.md
Labels: hash

#76 Programmers / [level 2] 위장
  README.md
  프로그래머스/같은숫자는싫어/Solution.java
  프로그래머스/같은숫자는싫어/같은 숫자는 싫어.md
  프로그래머스/기능개발/Solution.java
  프로그래머스/기능개발/기능개발.md
  프로그래머스/위장/Solution.java
  프로그래머스/위장/위장.md
Labels: hash

#77 Programmers / [level 2] 기능개발 , Programmers / [level 1] 같은 숫자는 싫어
  README.md
  프로그래머스/같은숫자는싫어/Solution.java
  프로그래머스/같은숫자는싫어/같은 숫자는 싫어.md
  프로그래머스/기능개발/Solution.java
  프로그래머스/기능개발/기능개발.md
  프로그래머스/위장/Solution.java
  프로그래머스/위장/위장.md
Labels: stack

#78 Programmers / [level 4] 도둑질
  도둑질/도둑질.md
  도둑질/도둑질.py
Labels: DP
