Repository CS-CT/Coding-Test, pull requests merged in 2023-09, with the labels that each got.

#104 Baekjoon / [Gold5] 최소비용 구하기, [Gold4] 알파벳, [Gold2] 피보나치수6, [Gold 1] 외판원 순회
  백준/알파벳/알파벳.java
  백준/알파벳/알파벳.md
  백준/외판원순회/외판원순회.java
  백준/외판원순회/외판원순회.md
  백준/최소비용구하기/최소비용구하기.java
  백준/최소비용구하기/최소비용구하기.md
  백준/피보나치수6/피보나치수6.java
  백준/피보나치수6/피보나치수6.md
Labels: DFS, BFS, DP, Dijkstra, bitmask

#105 Programmers / [level 1] Runner who Failed to Finish
  Jen/Runner who Failed to Finish/Runner who Failed to Finish.md
  Jen/Runner who Failed to Finish/Runner who Failed to Finish.py
Labels: implementation

#106 Programmers / [level 2] Phone Number List
  Jen/Phone Number List/Phone Number List.md
  Jen/Phone Number List/Phone Number List.py
Labels: implementation, hash

#107 BaekJoon / [Gold5] 다각형의 면적
  백준/다각형의면적/다각형의 면적.md
  백준/다각형의면적/다각형의면적.java
  백준/외판원순회/외판원순회.java
Labels: implementation

#108 BaekJoon / [Gold4] 스도쿠
  백준/세용액/세용액.java
  백준/세용액/세용액.md
  백준/스도쿠/스도쿠.java
  백준/스도쿠/스도쿠.md
Labels: implementation, DFS

#109 BaekJoon / [Gold3] 음악프로그램
  백준/음악프로그램/음악프로그램.java
  백준/음악프로그램/음악프로그램.md
Labels: topological sorting

#110 Programmers / [level 2] Clothes
  Jen/Clothes/Clothes.md
  Jen/Clothes/Clothes.py
  Jen/Phone Number List/Phone Number List.md
Labels: implementation, hash

#111 BaekJoon / [Gold1] 열쇠
  백준/열쇠/열쇠.java
  백준/열쇠/열쇠.md
Labels: implementation

#112 BaekJoon / [Gold3] 텀 프로젝트
  백준/텀프로젝트/텀 프로젝트.md
  백준/텀프로젝트/텀프로젝트.java
  백준/팰린드롬/팰린드롬.java
  백준/팰린드롬/팰린드롬.md
Labels: DFS, DP

#113 BaeKJoon / [Gold3] 행렬 곱셈 순서
  백준/행렬곱셈순서/행렬 곱셈 순서.md
  백준/행렬곱셈순서/행렬곱셈순서.java
Labels: DP
