Repository CS-CT/Coding-Test, pull requests merged in 2023-02, with the labels that each got.

#5 Programmers
  Jen/Small Substring/Small Substring.md
  Jen/Small Substring/Small Substring.py
Labels: implementation

#7 Programmers
  Jen/Coke Quiz/Coke Quiz.md
  Jen/Coke Quiz/Coke Quiz.py
Labels: implementation

#8 BaekJoon Gold5 5430.AC
  MJ/AC/AC.md
  MJ/AC/AC.py
Labels: implementation

#10 Programmers lv 1. Phonkémon
  Jen/Coke Quiz/Coke Quiz.md
  Jen/Phonkémon/Phonkémon.md
  Jen/Phonkémon/Phonkémon.py
  MJ/SampleFile.md
  README.md
Labels: implementation

#11 MJ branch update
  Jen/Coke Quiz/Coke Quiz.md
  Jen/Coke Quiz/Coke Quiz.py
  MJ/AC/AC.md
  MJ/AC/AC.py
  README.md
Labels: setting

#13 Programmers lv 1. Phonkémon
  Jen/Coke Quiz/Coke Quiz.md
  Jen/Phonkémon/Phonkémon.md
  Jen/Phonkémon/Phonkémon.py
  MJ/AC/AC.md
  MJ/AC/AC.py
  MJ/SampleFile.md
Labels: implementation, setting

#17 reupload AC problem
  MJ/AC/AC.md
  MJ/AC/AC.py
  MJ/SampleFile.md
Labels: implementation

#18 BaekJoon Gold 5 5430.AC
  MJ/AC/AC.md
  MJ/AC/AC.py
  MJ/SampleFile.md
Labels: implementation, setting

#23 Chore : Delete MJ
  .DS_Store
  MJ/AC/AC.md
  MJ/AC/AC.py
  MJ/SampleFile.md
Labels: setting

#24 Programmers lv 1. Caesar Cipher
  Jen/Caesar Cipher/Caesar Cipher.md
  Jen/Caesar Cipher/Caesar Cipher.py
Labels: implementation

#25 Programmers lv 1. Caesar Cipher
  Jen/Caesar Cipher/Caesar Cipher.md
  Jen/Caesar Cipher/Caesar Cipher.py
Labels: implementation

#26 Programmers
  Jen/Find Prime Numbers/Find Prime Numbers.md
  Jen/Find Prime Numbers/Find Prime Numbers.py
  Jen/Pick Two and Plus/Pick Two and Plus.md
  Jen/Pick Two and Plus/Pick Two and Plus.py
Labels: exhaustive search

#27 BaekJoon Gold2 1202.보석도둑
  MJ/SampleFile.md
  MJ/보석도둑/보석도둑.md
  MJ/보석도둑/보석도둑.py
Labels: greedy, sorting

#28 BaekJoon
  AC/AC.md
  AC/AC.py
  README.md
  SampleFile.md
  구간합 구하기/구간합 구하기.md
  구간합 구하기/구간합 구하기.py
  보석도둑/보석도둑.md
  보석도둑/보석도둑.py
  줄세우기/줄세우기.md
  줄세우기/줄세우기.py
Labels: segment tree

#29 Programmers
  Jen/Dart Game/Dart Game.md
  Jen/Dart Game/Dart Game.py
Labels: exhaustive search

#32 Chore : Update README.md
  README.md
Labels: setting

#30 Programmers / [level 2] 미로탈출
  README.md
  미로탈출/미로탈출.md
  미로탈출/미로탈출.py
Labels: BFS, shortest path

#31 백준 / 데이터구조
  README.md
  SampleFile.md
  백준/LCA/LCA.md
  백준/LCA/Main.java
  백준/데이터구조/Main.java
  백준/데이터구조/데이터구조.md
Labels: segment tree

#33 Programmers lv 2. Removing Pairs
  Jen/Correct Parentheses/Correct Parentheses.md
  Jen/Correct Parentheses/Correct Parentheses.py
  Jen/Removing Pairs/Removing Pairs.md
  Jen/Removing Pairs/Removing Pairs.py
Labels: stack

#34 Programmers / [level 2] 택배 배달과 수거하기
  택배 배달과 수거하기/택배 배달가 수거하기.py
  택배 배달과 수거하기/택배 배달과 수거하기.md
Labels: greedy

#35 Programmers / Lv. 2
  JT/SampleFile.md
  JT/두 큐 합 같게 만들기/두 큐 합 같게 만들기.md
  JT/두 큐 합 같게 만들기/두 큐 합 같게 만들기.py
  JT/롤케이크 자르기/롤케이크 자르기.md
  JT/롤케이크 자르기/롤케이크 자르기.py
  JT/연속 부분 수열 합의 개수/연속 부분 수열 합의 개수.md
  JT/연속 부분 수열 합의 개수/연속 부분 수열 합의 개수.py
  JT/택배 배달과 수거하기/택배 배달과 수거하기.md
  JT/택배 배달과 수거하기/택배 배달과 수거하기.py
  JT/할인 행사/할인 행사.md
  JT/할인 행사/할인 행사.py
Labels: greedy, hash, two pointer, prefix sum

#36 BaekJoon / [Platinum 5] LCA2
  SampleFile.md
  백준/LCA2/LCA2.md
  백준/LCA2/Main.java
Labels: LCA

#37 Programmers / [level 2] 조이스틱
  조이스틱/조이스틱.md
  조이스틱/조이스틱.py
Labels: DFS

#39 Programmers / [level 2] Life Boat
  Jen/Life Boat/Life Boat.md
  Jen/Life Boat/Life Boat.py
Labels: greedy

#40 Programmers / [level 2] 큰수만들기
  큰수만들기/큰수만들기.md
  큰수만들기/큰수만들기.py
Labels: greedy
