Repository CS-CT/Coding-Test, pull requests merged in 2023-04, with the labels that each got.

#79 Programmers / [level 2] 더맵게, [level 4] 도둑질
  프로그래머스/더맵게/Solution.java
  프로그래머스/더맵게/더맵게.md
  프로그래머스/도둑질/Solution.java
  프로그래머스/도둑질/도둑질.md
Labels: DP, heap

#81 Programmers / [level 1] Walk in the Park
  Jen/Walk in the Park/Walk in the Park.cpp
  Jen/Walk in the Park/Walk in the Park.md
  Jen/Walk in the Park/Walk in the Park.py
  README.md
Labels: implementation

#80 Programmers / [level 3] 파괴되지 않은 건물, [level 2] 기지국 설치
  JT/광물 캐기/광물 캐기.py
  JT/기지국 설치/기지국 설치.md
  JT/기지국 설치/기지국 설치.py
  JT/당구연습/당구연습.py
  JT/숫자 게임/숫자 게임.py
  JT/스타트와 링크/스타트와 링크.py
  JT/최고의 집합/최고의 집합.py
  JT/파괴되지 않은 건물/파괴되지 않은 건물.md
  JT/파괴되지 않은 건물/파괴되지 않은 건물.py
Labels: implementation, prefix sum

#85 Programmers / [level 1] 체육복
  프로그래머스/체육복/Solution.java
  프로그래머스/체육복/체육복.md
Labels: greedy

#86 Programmers / [level 2] 타겟 넘버, Programmers / [level3] 입국심사, BaekJoon / [Gold1] 구슬탈출 2
  백준/구슬탈출2/구슬탈출2.java
  백준/구슬탈출2/구슬탈출2.md
  프로그래머스/입국심사/Solution.java
  프로그래머스/입국심사/입국심사.md
  프로그래머스/타겟넘버/Solution.java
  프로그래머스/타겟넘버/타겟넘버.md
Labels: DFS, BFS, binary search

#87 CodeTree / [Gold 4] 격자 숫자 놀이
  격자 숫자 놀이/격자 숫자 놀이.md
  격자 숫자 놀이/격자 숫자 놀이.py
Labels: implementation
